#ifndef ILLUSION_PATH_TRACING_SCREEN_INPUTS_INCLUDED
#define ILLUSION_PATH_TRACING_SCREEN_INPUTS_INCLUDED

#undef SHADERGRAPH_SAMPLE_SCENE_COLOR
#define SHADERGRAPH_SAMPLE_SCENE_COLOR(uv) float3(0, 0, 0)
#undef SHADERGRAPH_SAMPLE_SCENE_DEPTH
#define SHADERGRAPH_SAMPLE_SCENE_DEPTH(uv) UNITY_RAW_FAR_CLIP_VALUE

#endif
