#ifndef ILLUSION_PATH_TRACING_RAYGEN_INCLUDED
#define ILLUSION_PATH_TRACING_RAYGEN_INCLUDED


#define TARGET_D3D12
#define ENABLE_DEBUG_VIZUALISATIONS 0
#define ENABLE_DEBUG_LINES_VIZ 0
#define PT_NEE_ENABLED 1
#define NEE_AT_SAMPLE_BAKED_ENVIRONMENT 0
#define PT_ENABLE_RUSSIAN_ROULETTE 1
#define PT_USE_RESTIR_DI 0
#define PT_USE_RESTIR_GI 0
#define RTXPT_USE_APPROXIMATE_MIS 0
#define RTXPT_NEE_FULL_SAMPLE_COUNT 1
#define RTXPT_NEE_LOCAL_CANDIDATE_SAMPLE_COUNT 3
#define RTXPT_NEE_GLOBAL_CANDIDATE_SAMPLE_COUNT 2
#define RTXPT_NEE_TOTAL_CANDIDATE_SAMPLE_COUNT 5
#define RTXPT_DISCARD_NON_NEE_LIGHTING 0
#define RTXPT_DISCARD_NEE_LIGHTING 0
#define RTXPT_FIREFLY_FILTER 1
#define RTXPT_ACTIVE_STABLE_PLANE_COUNT 3
#define RTXPT_NESTED_DIELECTRICS_QUALITY 1
#define RTXPT_LP_TYPES_USE_16BIT_PRECISION 0
#define RTXPT_ENABLE_LOW_DISCREPANCY_SAMPLER_FOR_BSDF 1

#include "Packages/com.kurisu.illusion-render-pipelines/ShaderLibrary/PathTracing/RTXPT/PathTracerSample.hlsl"

#endif
